inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

require:
  - rubocop-rake
  - rubocop-rspec

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Gemspec/RequireMFA:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 30

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  MaxOptionalParameters: 5
