inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

require:
  - rubocop-rake
  - rubocop-rspec

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Gemspec/RequireMFA:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false
